params1:
    loss: "cross_entropy"
    optimiser: "sgd"
    batch_size: 256
    num_epochs: 5
    learning_rate: 0.1
    weight_decay: 0.001
    momentum: 0.9
    num_hidden: 2
    hidden_size: 64
    activation: "relu"
    dropout_rate: 0.8
    batch_normalisation: True

params2:
    loss: "cross_entropy"
    optimiser: "sgd"
    batch_size: 128
    num_epochs: 20
    learning_rate: 0.1
    weight_decay: 0.0
    momentum: 0.0
    num_hidden: 2
    hidden_size: 64
    activation: "relu"
    dropout_rate: 0.8
    batch_normalisation: False

grid1:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64]
    num_epochs: [15]
    learning_rate: [0.1]
    weight_decay: [0]
    momentum: [0]
    num_hidden: [2]
    hidden_size: [64]
    activation: ["relu"]
    dropout_rate: [0]
    batch_normalisation: [False]

grid2:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64, 256]
    num_epochs: [2, 5]
    learning_rate: [0.01, 0.1]
    weight_decay: [0]
    momentum: [0]
    num_hidden: [2]
    hidden_size: [64, 128]
    activation: ["relu"]
    dropout_rate: [0]
    batch_normalisation: [False]

grid-search1:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64, 256]
    num_epochs: [10, 40, 100]
    learning_rate: [0.01, 0.1]
    weight_decay: [0, 0.001, 0.0001]
    momentum: [0, 0.5, 0.9]
    num_hidden: [2]
    hidden_size: [64, 128]
    activation: ["relu"]
    dropout_rate: [0, 0.3]
    batch_normalisation: [False, True]
