params1:
    loss: "cross_entropy"
    optimiser: "sgd"
    batch_size: 256
    num_epochs: 1
    learning_rate: 0.1
    weight_decay: 0
    momentum: 0.9
    num_hidden: 2
    hidden_size: 64
    activation: "relu"
    dropout_rate: 0
    batch_normalisation: True

params-best:
    loss: "cross_entropy"
    optimiser: "sgd"
    batch_size: 64
    num_epochs: 300
    learning_rate: 0.1
    weight_decay: 0.0
    momentum: 0.9
    num_hidden: 4
    hidden_size: 256
    activation: "relu"
    dropout_rate: 0.3
    batch_normalisation: True

grid-local:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [256]
    num_epochs: [180]
    learning_rate: [0.01]
    weight_decay: [0.0001]
    momentum: [0.5]
    num_hidden: [2]
    hidden_size: [128, 256]
    activation: ["relu"]
    dropout_rate: [0]
    batch_normalisation: [False]

grid1:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64]
    num_epochs: [100]
    learning_rate: [0.01]
    weight_decay: [0.0001]
    momentum: [0.5]
    num_hidden: [2,3,4]
    hidden_size: [128]
    activation: ["relu"]
    dropout_rate: [0]
    batch_normalisation: [False]

grid2:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [256]
    num_epochs: [5]
    learning_rate: [0.1]
    weight_decay: [0]
    momentum: [0.9]
    num_hidden: [2]
    hidden_size: [128]
    activation: ["relu"]
    dropout_rate: [0.3]
    batch_normalisation: [True]

grid-nan:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [256]
    num_epochs: [100]
    learning_rate: [0.1]
    weight_decay: [0.0001]
    momentum: [0.9]
    num_hidden: [2]
    hidden_size: [64]
    activation: ["relu"]
    dropout_rate: [0.3]
    batch_normalisation: [False]

grid-search1:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64, 256]
    num_epochs: [10, 40, 100]
    learning_rate: [0.01, 0.1]
    weight_decay: [0, 0.001, 0.0001]
    momentum: [0, 0.5, 0.9]
    num_hidden: [2]
    hidden_size: [64, 128]
    activation: ["relu"]
    dropout_rate: [0, 0.3]
    batch_normalisation: [False, True]

grid-search2:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64]
    num_epochs: [200, 300]
    learning_rate: [0.1]
    weight_decay: [0]
    momentum: [0.9. 0.95]
    num_hidden: [3, 4]
    hidden_size: [128, 256]
    activation: ["relu"]
    dropout_rate: [0.3, 0.5]
    batch_normalisation: [True]

grid-search3:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [64]
    num_epochs: [300, 600, 1200]
    learning_rate: [0.1]
    weight_decay: [0]
    momentum: [0.9]
    num_hidden: [4]
    hidden_size: [256, 512]
    activation: ["relu"]
    dropout_rate: [0.3]
    batch_normalisation: [True]

grid-ablation:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [8, 16, 32, 64, 128, 256, 512, 1024]
    num_epochs: [1, 5, 20, 50, 100, 150, 200, 300, 450]
    learning_rate: [0.00001, 0.0001, 0.001, 0.01, 0.1, 0.5]
    weight_decay: [0, 0.00001, 0.0001, 0.001, 0.01, 0.1]
    momentum: [0, 0.2, 0.5, 0.7, 0.9, 0.99]
    num_hidden: [0, 1, 2, 3, 4, 5, 6]
    hidden_size: [2, 16, 64, 128, 256, 512, 1024]
    activation: ["relu"]
    dropout_rate: [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75]
    batch_normalisation: [False, True]

grid-ablation2:
    loss: ["cross_entropy"]
    optimiser: ["sgd"]
    batch_size: [1, 64]
    num_epochs: [100]
    learning_rate: [0.1]
    weight_decay: [0, 0.001]
    momentum: [0, 0.9]
    num_hidden: [0, 4]
    hidden_size: [128]
    activation: ["relu"]
    dropout_rate: [0, 0.3]
    batch_normalisation: [False, True]